"""empty message

Revision ID: 094559e38014
Revises: d7f8cfc796f8
Create Date: 2020-02-11 09:42:04.382409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094559e38014'
down_revision = 'd7f8cfc796f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loglist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loglist')
    # ### end Alembic commands ###
